### ISSUE TITLE
Full width template for single download 

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/themedd#108]
Just It, a full width template (with no sidebar) for single download pages

**Comment by rubengc** [comment]
Also I noticed that themedd always force to have the sidebar with some default items, why not keep same functionality applied to sidebar-1? (if this sidebar is empty then page will look as full width)

**Comment by davidsherlock** [comment]
@rubengc, I like this idea but there would need to be some kind of fallback for the purchase options and purchase button to display somewhere on the content when the sidebar was disabled.

**Comment by amdrew** [comment]
> Just It, a full width template (with no sidebar) for single download pages

Since Themedd is more geared towards a "starting point", having another full width template just for single download pages introduces a lot more complexities. As David mentioned we would then need to think about where the purchase button would go (probably below the content where EDD places it by default). 

We also need to think about the price, download details and author details. There are also other things added by other extensions. All this would require more CSS styling for positioning and responsiveness and is a lot more to maintain going forward. Having a sidebar is the "safe" option that provides the greatest flexibility and is typically what someone would expect.

It's much simpler to leave this decision to those that actually need/want it. There's actually no need to create a new template, you can copy the Full Width template included to the child theme and add `Template Post Type: page, download` to the comment. The same full width template file can then be used for pages and downloads (could even use it for posts). See: https://make.wordpress.org/core/2016/11/03/post-type-templates-in-4-7/

Sidenote: In Themedd you can programmatically hide the sidebar (for all downloads or only some) without the need for a template. A page template would need to be assigned to every single download.

> Also I noticed that themedd always force to have the sidebar with some default items, why not keep same functionality applied to sidebar-1? (if this sidebar is empty then page will look as full width)

Borrowed this logic from the Vendd theme. A product will always have a sidebar since it needs a price and purchase button. If there are categories or tags assigned they are also shown by default. This allows no extra work on the end user's behalf, since they can simply install the theme and start adding downloads. The same applies to when Frontend Submissions is active. Author details will automatically appear. 

If the end user does decide to drag a widget into the download sidebar it lets them have full control. They can rebuild the sidebar and rearrange the widgets to get the exact layout they are after.

If there's no sidebar, where does all the information display?
