### ISSUE TITLE
h3.edd_download_title tweak suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#130]
The download title feels a bit far away from the excerpt because it's using a margin-bottom of `1.62rem`. I think the following looks better, more 'connected' and cohesive:

```
h3.edd_download_title {
    margin-top: 0;
    margin-bottom: 0.81rem;
}
```

**Comment by amdrew** [comment]
@davidsherlock Let's go with 1rem (16px). Other things affect the spacing such as download meta, so don't want to go too small. Here's 1rem shown with download meta at different positions:

<img width="1234" alt="screenshot 2017-09-19 20 14 07" src="https://user-images.githubusercontent.com/52581/30582286-45859632-9d77-11e7-97ff-7b3b0d0d469e.png">

In the first download the download title has 1rem of bottom margin (no excerpt to illustrate).

In the second download there's 0.5rem of bottom margin because of the download meta. The download meta then has 1rem of bottom margin.

In the third download you can see the 1rem of bottom margin before the excerpt.

**Comment by amdrew** [comment]
That should do it. Refactored the CSS to be more flexible. The position of the download meta is now outputted to the main download class.
