### ISSUE TITLE
Default EDD actions hooks being removed (or filtered) on taxonomy pages

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#132]
I am in the process of putting together an audio player plugin for EDD and everything is working great, except one thing - on the taxonomy pages (categories and tags) within Themedd, the default hooks aren't present (or being removed).

Working perfectly everywhere else, except those pages. I am using the following:

```
/**
 * Download item after hook
 */
function edd_download_actions_edd_download_after() {
    global $edd_download_shortcode_item_atts, $edd_download_shortcode_item_i;

    if ( 'yes' === $edd_download_shortcode_item_atts['audio'] ) {
        edd_render_download_audio_files();
    }
}
add_action( 'edd_download_after_title', 'edd_download_actions_edd_download_after' );
```

**Comment by amdrew** [comment]
@davidsherlock The `edd_download_after_title` hook exists on the taxonomy pages, so if you echo something out (outside of your conditional) you'll see it appears. Are you perhaps misunderstanding how taxonomy pages work? 

From your code it looks like you are filtering the downloads shortcode and adding a new `audio` attribute. Is that correct? 

If so, how would adding a `[downloads audio="yes"]` shortcode onto any page in WordPress affect the taxonomy pages, which don't use shortcodes (because there's no where to add them)?

**Comment by davidsherlock** [comment]
@amdrew, close this one off - my mistake! I forgot the approach I took (shortcode attributions) had limitations on the taxonomy pages. Will build a fallback for that - apologise for opening this thread!
