### ISSUE TITLE
Allow filtering of sidebars

### ISSUE THREAD

**Issue by amdrew** [easydigitaldownloads/themedd#157]
PR from @flowdee: https://github.com/easydigitaldownloads/themedd/pull/154/files

> New filter in order to allow adding more custom sidebars, while making use of the existing registration workflow

@flowdee Thanks for the PR. While I don't see the need for a new filter _just_ to add sidebars (since you can just use `register_sidebar()`), I do see where you are coming from. Any new sidebar created with the filter hook would pick up the default `$widget_tags` options. Was that your intention?

Another benefit would be updating the existing sidebar options. Using the download sidebar as an example, a developer could tweak `before_widget`, `after_widget`, `before_title`, `after_title` etc of each widget on a single download page which would allow more creative freedom.

**Comment by flowdee** [comment]
Yeah exactly @amdrew . Otherwise I would have to care about multiple places in the code. 

e.g. I personally don't use h2 as widget title. That's why I already hook into your filters in order to update the widget tags. When adding new sidebars. When adding custom sidebars, I would have another block of code where I setup the widget tags.

**Comment by amdrew** [comment]
Merged

**Comment by flowdee** [comment]
Awesome! Thanks Andrew 👍
