### ISSUE TITLE
Schema structure broken on download pages

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/themedd#181]
On single download page, the product title is moved up into a header position. The product title has `itemprop="name"` added to it for schema purposes, which should be inside of `itemscope itemtype="http://schema.org/Product"` in the HTML structure. Moving the title produces an error where the product has no "name" in the schema structure.

Here's a testing tool: https://search.google.com/structured-data/testing-tool/u/0/

Try this URL: https://successstories.themedd.com/products/money-money-money/

Might be worth it to also test a popular schema adding WP plugin or something (assuming those exist) to see if it's gonna break on things like standard pages.

**Comment by amdrew** [comment]
@SDavisMedia Started implementing a fix for this by disabling EDD's open and close wrappers, and then adding the `itemscope itemtype="http://schema.org/Product"` directly to Themedd's `content` div so it encompasses the entire product div. 

Then started working on fixing up the schema for the price that lives outside of the purchase button, but quickly ran into an issue whereby the schema from EDD was incorrect (mentioned also by Kyle on the issue linked below). Basically, the currency symbol needs to be separated with its own `span`.

https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5240 proposes that EDD core move from microdata to JSON-LD. After looking into JSON-LD is more detail, it's much, much easier. This would solve all schema issues in EDD as well as the schema issues in Themedd. It also means less `span`'s scattered throughout the code.

Rather than adding more code in Themedd to get the microdata near-perfect (since EDD core is still broken), the better option is to wait for EDD core to adapt JSON-LD. In fact, for the time-being it might actually make sense to disable microdata altogether in Themedd.

**Comment by SDavisMedia** [comment]
@amdrew Think we can disable schema in Themedd and wrap up 1.0.5 soon?

**Comment by amdrew** [comment]
@SDavisMedia Yes, disabling schema temporarily until JSON-LD lands in core (3.0 hopefully 🤞 ) seems like the best approach. I'll make it a priority to get 1.0.5 out the door, hopefully today or tomorrow.

**Comment by amdrew** [comment]
Fixed via https://github.com/easydigitaldownloads/themedd/commit/bfa77418d4d0400429c1266d057042cc3f3671fa

**Comment by Njengah** [comment]
This issue is still there how do I fix it  ?

**Comment by cklosowski** [comment]
@Njengah On the latest version of Themedd? If so could you please contact our support team so we can get a little more information from you?

https://easydigitaldownloads.com/support
