### ISSUE TITLE
FES Vendor profile page template

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#21]
I am not sure to what extent Themedd is going to be an "all-in-one" EDD/FES theme/framework, but it would be a good idea to have a dedicated template for the FES Vendor profile page that includes the contact form at the bottom and profile section at the top like the Vendd theme has. This would allow the avatar, short vendor bio, URL, etc to be shown along with the EDD products.

**Comment by amdrew** [comment]
Absolutely, it'll support FES as much as possible so it will definitely need its own template to do the contact form etc.

**Comment by amdrew** [comment]
Going to tackle this next!

**Comment by amdrew** [comment]
First pass:

There's no need to set a page template since FES already allows you to specify which page should be the vendor page. Make sure you've selected a vendor page in FES's settings and you're good to go. The new template (`template-parts/vendor-page.php`) is therefore applied dynamically. 

The form styling is a bit icky at the moment due to the way FES loads its CSS file, which cannot be removed using `wp_dequeue_style()`. As a result, Themedd's form styling is being overridden from FES's CSS file in the footer. Will open an issue on the FES repo for this.

![screen shot 2017-06-28 at 10 16 09 pm](https://user-images.githubusercontent.com/52581/27632365-9aa54748-5c4f-11e7-89d7-0323de372b74.png)

There's a new customizer setting for controlling the display of the contact form:

![screen shot 2017-06-28 at 10 16 35 pm](https://user-images.githubusercontent.com/52581/27632364-9a9de98a-5c4f-11e7-9995-9053ce3e8bf8.png)

And finally, if the user _does_ decide to use one of Themedd's page templates on the vendor page, the contact form (if enabled) will reposition itself at the bottom of the page. It will be wide, or slim, depending on the page template selected.
![screen shot 2017-06-28 at 10 30 00 pm](https://user-images.githubusercontent.com/52581/27632929-5f26c870-5c51-11e7-99ca-1aa798f6a703.png)

**Comment by davidsherlock** [comment]
Will give this a test today Andrew! Quick question, do you intend to add social profile links to the vendor page as per Vendd?

**Comment by amdrew** [comment]
Absolutely, all things social will be covered in https://github.com/easydigitaldownloads/themedd/issues/57

**Comment by davidsherlock** [comment]
@amdrew, for the life of me i can't get this to work. I've tried assigning and reassigning the vendor page, but nothing seems to work to show the bio and contact form. The products "appear" to show correctly for the vendor (admin - also a vendor), but no luck getting what you are getting...

**Comment by amdrew** [comment]
@davidsherlock Can you show me what you see for the vendor page? Have enabled the customizer option to show the contact form?

**Comment by amdrew** [comment]
Probably something I did, let me dig deeper.

**Comment by davidsherlock** [comment]
Got it working! Strangely by default that option was set by theme but wasn't being applied since it probably wasn't saved/loaded properly. I applied it and the on the full-width (no sidebar) page the contact form appeared at the bottom (cool!).

However on all the other pages featuring the `[downloads]` shortcode this now shows:

`No vendors ID set!`

**Comment by amdrew** [comment]
^ That will fix the first issue. Just replicated the `No vendors ID set! `, good catch.

**Comment by amdrew** [comment]
Ok that should do it.

**Comment by davidsherlock** [comment]
Perfect! Working good now @amdrew.

**Comment by davidsherlock** [comment]
I'm aware this is a design decision, but I can't help but feel the author name (maybe the display name?) should be shown above the contact form. The store name makes sense at the top of the page, but maybe the actual person you are contacting makes more sense on the sidebar above the bio. What you think yourself?

**Comment by davidsherlock** [comment]
It also says "Vendor Contact" when "Contact Vendor" makes more sense.

**Comment by davidsherlock** [comment]
@amdrew, can you add a class to the contact form so it's easy to style for?

`primary-sidebar widget-area fes-contact-form` or something?

**Comment by amdrew** [comment]
> I'm aware this is a design decision, but I can't help but feel the author name (maybe the display name?) should be shown above the contact form. The store name makes sense at the top of the page, but maybe the actual person you are contacting makes more sense on the sidebar above the bio. What you think yourself?

I agree that it does need to show either the store name (again) or the vendor's name, Just not sure on which yet. Going to sit on it for a while.

> It also says "Vendor Contact" when "Contact Vendor" makes more sense.

This is coming from FES. I agree, sounds backwards, will see if it's filterable.

> can you add a class to the contact form so it's easy to style for?

It's not possible to add classes directly to the form element, only what FES outputs. Why can't just use the classes already provided? You can target the form already using:

`.fes-vendor-contact-form { ... }`

Or if you need to be more specific, `primary-sidebar .fes-vendor-contact-form { ... }`

**Comment by amdrew** [comment]
The title on the contact form can be filtered. I'll change it by default to `Contact vendor` or similar.

**Comment by davidsherlock** [comment]
Sorry Andrew, I mean the sidebar itself! Something like fes-sidebar would be fine.

If not, I can do this in my child theme!

**Comment by amdrew** [comment]
Absolutely! Haven't quite finished yet so I'll sort out a class for the widget `section` that contains all the vendor stuff. Or I might add a body class which could provide more flexibility.

**Comment by davidsherlock** [comment]
@amdrew, what are your thoughts on adding the Author name to the sidebar under the avatar? Feel it's needed since this is "who" you are contacting.

**Comment by amdrew** [comment]
Yep will do it

**Comment by amdrew** [comment]
I've added a `edd-fes-vendor-page` class to the body tag. This will allow targeting of the sidebar, as well as any other element on the page.

**Comment by Mor-raj** [comment]
Hi @amdrew
Is there any way to show FES vendor in EDD receipt too?
Thanks

**Comment by Mor-raj** [comment]
Hi @amdrew
Can you help me, please...?

Regard

**Comment by amdrew** [comment]
@Mor-raj Sorry for the delay in replying. 

This issue was related to the FES vendor profile page and how it displays within the theme, Themedd. 

You'll likely need some custom development to modify the behavior of the purchase receipt in EDD (and retrieve the relevant information from FES) so I'd suggest reaching out to an EDD consultant to get this built for you: https://easydigitaldownloads.com/consultants/
