### ISSUE TITLE
Advanced search results suggestion

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#30]
The Vendd theme has the ability to enable an "advanced search results" mode which replaces the standard blog/list archive search page with a column based product layout, and the associated pages/posts at the bottom with no feature images present.

This has many benefits on page size, since the large featured images aren't required to be loaded (the smaller grid ones are used) and since most people will be using the theme for download stores and this would be expected the results layout.

This option would be useful within the "Easy Digital Downloads" section within the customizer.

**Comment by amdrew** [comment]
Will take a look at how Vendd does it. Going to tag for future release for now. If I have time I'll implement it, otherwise it will come soon after.

**Comment by davidsherlock** [comment]
@amdrew, since Themedd is ultimately aimed at EDD, I feel this is somewhat of an essential feature for the theme.

My thinking is that within the Easy Digital Downloads settings (in Themedd), the option can be made available to enable an advanced search mode. This way @SDavisMedia handled it via Vendd was perfect in my opinion, with the downloads at the top and the posts/pages at the bottom in seperate columns.

Would be good to see this make it into 1.0.1...just saying :grin:

**Comment by amdrew** [comment]
@davidsherlock 1.0.1 is geared towards small bugs etc so this issue won't make it in :)

**Comment by davidsherlock** [comment]
:cry:

**Comment by amdrew** [comment]
Going to try and get this into 1.0.3 since it would nicely complement the header search box being introduced.

I'm not yet sold on the idea of an "advanced search results" option. My thinking is if EDD is installed and active, downloads should automatically be shown in a grid (above all other search results) for the customer. Mainly because 1) it's a store with products being sold and 2) An image made for the download grid may not look very nice on the search results page in a barebones listing.

Also undecided on listing out the pages and posts without featured images etc, that could come later. Mainly want to focus on the downloads for now.

**Comment by davidsherlock** [comment]
Well this is good news @amdrew! Definitely will make the theme more unified and specific to it's purpose.

I'm not entirely sold on the advanced search mode either, adds an unneeded option in the customizer. The way proposed above seems the best route (download products only - if EDD is active).

**Comment by amdrew** [comment]
There's a bit of an issue with this approach. While it's technically possible to group downloads together and show them above all other search results, it will eventually lead to issues, mainly with pagination.

In order to group the downloads, posts, and pages separately, you need to perform some wizardry to group each post type. Naturally, you'll want to show _all_ posts of each post type, otherwise you would have 3 sets of pagination (which is part of the problem). Now, what happens when there are hundreds, or thousands of each post type? Unlikely to happen, but it could happen.

You might then decide to show pagination only for the downloads, but when you hit page 2 of the downloads, while showing posts and pages, things are likely going to break with pagination. At least from what I've seen in my research. I have yet to come across a clean solution that still works with pagination.

As an example, imagine a site with 1000 downloads, which are searchable by the term "book" (perhaps it's in the title). If a customer searches for "book" they are going to get served a download grid with 1000 downloads, then all the posts, then all the pages below. This may be an unlikely scenario but there are some sites out there with many, many downloads and we cannot possibly know what is going to be displayed for a given search term.

Couple the above with the fact that many end-users will be using a dedicated search plugin and things could get messy. Pagination will break, or the browser will crash with the number of downloads shown. It would be much better to _not_ modify the search query too much and keep things simple.

## Here's what I think we should do instead:

We add a new admin checkbox option in the Easy Digital Downloads customizer section. This would be called "Search Downloads Only" or similar and be related to the header search box option being introduced. 

With this option enabled, any search query from the new header search box will _only_ search downloads. The search results page would then display a download grid with the normal EDD pagination if required. Additionally, the placeholder of the search field would say "Search products" rather than the standard "Search".

A search query from any other search field around the site would result in the normal search results, including posts, pages etc. These would be displayed as normal. Currently the search results page is wide, I think this should now be slim so everything looks a bit nicer.

I did think about showing downloads first in the normal search results (really easy using the `posts_search_orderby` filter) however that's changing the search too much IMO. If a customer genuinely wanted to find posts and they were served a mass of downloads first, it would be very frustrating. The search in the header of an eCommerce site is more or less expected to search the products, at least from what I've seen.

**Comment by davidsherlock** [comment]
@amdrew, i agree with the above! Searching the products makes the most sense.

**Comment by amdrew** [comment]
Merged into master for more testing.

New admin option:

<img width="345" alt="screenshot 2017-10-07 00 16 39" src="https://user-images.githubusercontent.com/52581/31275747-d49926a6-aaf4-11e7-8bcd-f56881e6ea00.png">

In the future I'll hide the option if the header search box is not enabled.

**Comment by davidsherlock** [comment]
@amdrew, for some reason this isn't working for me. It's just displaying the results as per normal (in a list) rather than a grid. Option is enabled in the customizer.

**Comment by amdrew** [comment]
Yeah sorry just noticed that also. Should be fixed in latest commit :)

**Comment by davidsherlock** [comment]
Working well here @amdrew! My OCD did kick in somewhat thinking it should be "Search downloads" rather than "Products". But "Products" makes the most sense in this context.

**Comment by amdrew** [comment]
I hear you, I really wanted to use "Downloads", but 9 times out of 10 the end-user will probably expect "Products". Would have also meant yet another admin option. There's a `themedd_header_search_box_text` filter in there if someone wants to change it to something else.

**Comment by amdrew** [comment]
Closing
