### ISSUE TITLE
Add customizer option for the custom post type archive page (/downloads)

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#31]
Within the EDD section in the customizer, it would be useful to be able to set a title on the download archive page similar to Vendd.

If left blank, the title of the page will show instead. Allowed tags could be: `<a>, <span>, <em>, <strong>.`

**Comment by amdrew** [comment]
@davidsherlock Looking at Vendd, I'm not seeing a title or customizer option for the custom post type archive page, i.e `/downloads`:

<img width="1204" alt="screenshot 2017-06-20 21 11 51" src="https://user-images.githubusercontent.com/52581/27325605-17aac712-55fd-11e7-8123-9fbe14a7070c.png">

Also this won't have a page title since it's not an actual page. Are you referring to the `EDD Downloads Template Title` setting in Vendd?

**Comment by davidsherlock** [comment]
@amdrew, it's under the Easy Digital Downloads settings at the bottom if i recall correctly! It was confusing to me initially as well :)

**Comment by amdrew** [comment]
Correct me if I'm wrong but I think you may be referring to the "EDD Downloads Template Title" setting. Otherwise, I don't see any other setting. This text only shows on a page which has the `EDD Downloads` page template set for it. It doesn't change, or set a title on the download archive page (archive-download.php) which is `/downloads` by default.

![screen shot 2017-06-26 at 9 02 20 pm](https://user-images.githubusercontent.com/52581/27531988-c57a66a4-5ab2-11e7-9582-f40940ca3a7f.png)

![screen shot 2017-06-26 at 9 03 55 pm](https://user-images.githubusercontent.com/52581/27532031-fbdc0964-5ab2-11e7-95fb-052e055dbae7.png)

This is Vendd's download archive page (/downloads) which has no title:

![screen shot 2017-06-26 at 9 05 15 pm](https://user-images.githubusercontent.com/52581/27532097-32236c38-5ab3-11e7-9a40-97c6b32dd949.png)

That said, it would be nice to be able to Add a title to the download archive page, even if it's not used much by customers. Perhaps not an admin option just yet, code snippet for starters.

**Comment by SDavisMedia** [comment]
Vendd doesn't have a title on the `/downloads` archive. May be nice to add, though.

**Comment by davidsherlock** [comment]
@amdrew, could give you me a quick pointer (or example code) on how to best implement this in Themedd? Keen to add this to my theme, since i see it requested a lot.

**Comment by amdrew** [comment]
@davidsherlock Sure thing, load the `themedd_page_header()` function on the `themedd_content_start` action hook. You'll want to limit this to only the custom post type archive page. There's a `title` parameter you can pass to the page header function, or you might like to build out a customizer option for it.

**Comment by davidsherlock** [comment]
Perfect, thanks Andrew! I'll build out an option In the customiser for it.

**Comment by amdrew** [comment]
You're welcome! I'm not opposed to putting it in Themedd either, just going to sit on it for a while.

**Comment by davidsherlock** [comment]
@amdrew, part of me thinks this should be in the theme customizer by default under the EDD settings. What are your current thoughts on this?

**Comment by amdrew** [comment]
@davidsherlock I think it should 👍  If the page has been disabled via the `EDD_DISABLE_ARCHIVE` constant then the option will be hidden.

**Comment by amdrew** [comment]
By default I'm going to set the cpt archive's page title to the output of EDD's `edd_get_label_plural()` function. This will generally be `Downloads`. Anyone who has changed it to `Books` as an example will see `Books` as the page title, and will also see `Books` by default in the customizer's input field.

From there, the end-user can either remove the title altogether, in which case no page header will show (like how it is now), or change it to something else entirely like `Products`.

**Comment by amdrew** [comment]
There's another 2 options:

- Always providing a page title. If the input field in the customizer is cleared out and saved, it falls back to the plural label, usually "Downloads".

- Introducing the new customizer option, but leaving it blank. This provides no disruption to existing users. If they want to add a page title they can, otherwise it stays as-is.

@davidsherlock Which of the 3 options would you be keen to see?

**Comment by amdrew** [comment]
New input field looks like this currently (pending decision above):

<img width="341" alt="screenshot 2017-10-05 15 32 21" src="https://user-images.githubusercontent.com/52581/31208575-66142c84-a9e2-11e7-80c6-1bbfde938600.png">

Automatically shows the EDD plural label unless removed or changed. The URL will show the end-user's own URL to the CPT archive page.

**Comment by davidsherlock** [comment]
Nice! My vote would go to:

> Introducing the new customizer option, but leaving it blank. This provides no disruption to existing users. If they want to add a page title they can, otherwise it stays as-is.

Seems the most "expected" behaviour, as I can see instances where a person might not want it at all (like how it is at present).

**Comment by amdrew** [comment]
Yeah, I'll go with that option, thanks.

**Comment by amdrew** [comment]
This is good to go!, merged into master.
