### ISSUE TITLE
Mobile responsive issues

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#34]
Been testing out Themedd pretty extensively on my iphone 6s plus and discovered a few responsive issues. I will keep all current and future issues within this thread for ease of review.

Checkout table width issue:

![2017-06-17 16 01 16](https://user-images.githubusercontent.com/22668877/27256391-4fb84ca0-53ab-11e7-844c-5d67db4aa2ac.png)

Checkout form fields file upload fields would be better vertically stacked on smaller mobile devices (like here):

![2017-06-17 16 01 38](https://user-images.githubusercontent.com/22668877/27256393-57afaf3e-53ab-11e7-8bb7-7c837669b0a2.png)

I imported all the default WordPress post test data and this started happening on the blog archive page:

![2017-06-17 16 02 51](https://user-images.githubusercontent.com/22668877/27256451-d5557b7a-53ac-11e7-99a4-31787cd8f84d.png)

EDD Free downloads plugin mobile modal box dosen't have correct button colours as per theme customizer:

![2017-06-17 16 00 15](https://user-images.githubusercontent.com/22668877/27256454-e7fe9090-53ac-11e7-8310-de8dd51892d9.png)

**Comment by amdrew** [comment]
Thanks for the extensive testing, will check it out

**Comment by amdrew** [comment]
@davidsherlock Made some CSS tweaks to take care of the above. Overall site padding is lesser at mobile resolutions, as is table padding - should help a lot with mobile stuff.

The stacking of the file upload fields is a no-go. Since those are inside an HTML `table`, I'm not sure there's anything we can do, without re-doing all the markup.

Free downloads issue opened here:
https://github.com/easydigitaldownloads/edd-free-downloads/issues/164

Going forward, lets open a new issue for each styling issue, makes it easier to track and discuss.
