### ISSUE TITLE
Improved download archive/shortcode output

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#38]
The Vendd theme pretty much nailed the perfect way of displaying EDD products on the archive pages, home page, etc by overriding the default EDD shortcode templates and providing a togglable drawer.

While I understand the philosophy behind Themedd is to leave a lot of stuff up to the child theme and plugins discretion, it's actually a pretty usable theme out of the box for building EDD sites _as-is_.

With that said, if you have products with variable (or multi-part) pricing enabled the archive pages start to get messy (and large) due to the default behaviour of EDDs shortcode output, spacing, etc. The way Vendd handles this is arguably better by making a clickable open/close drawer like this:

![screenshot 2017-06-19 10 24 51](https://user-images.githubusercontent.com/22668877/27279286-18c1bc7c-54dc-11e7-90e5-59be0e9e9625.png)

Within the customizer for EDD settings, it would be useful to have the ability to enable a "compact" mode which uses the same approach to this where the price itself is consolidated into the buy button and a simple open/close toggle drawer is used to keep everything compact (including the pricing options).

**Comment by davidsherlock** [comment]
As a side note, the way the FES author is displayed within Vendd is also a good idea on the archive pages/EDD output.

![screenshot 2017-06-19 10 48 19](https://user-images.githubusercontent.com/22668877/27279552-e1363638-54dc-11e7-92f3-ef6d61b096dc.png)

**Comment by davidsherlock** [comment]
(ignore the custom styling - from a child theme I am building! haha)

**Comment by amdrew** [comment]
Theme looks nice!

Download author was added in this issue: https://github.com/easydigitaldownloads/themedd/issues/58

While it _can_ look cluttered with variable pricing options being outputted, there won't be any kind of JavaScript-driven drawer added to Themedd (but you already knew that :) ). At least the customer can choose not to output the purchase button to make things a bit tidier.

If I did include this in Themedd (and with an admin option), the functionality suddenly has to be supported by all child themes because the user that installed the child theme will expect it to be there (since it was in the parent theme). This introduces its own set of problems and limitations in design.

It would be much better implemented in a child theme which will also make the child theme look much more unique than its parent.
