### ISSUE TITLE
Responsive table support/issues

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#41]
Rather than post a bunch of responsive CSS issues, it's better to just open a single issue about this since they are all related to tables.

Because EDD/FES use tables throughout, mobile devices have issues because the tables aren't wrapped in a divs with `overflow-x: auto` set. 

Here are some screenshots taken from my iPhone 6s Plus to demonstrate the issues:

![2017-06-19 11 54 06](https://user-images.githubusercontent.com/22668877/27282091-6de1bdba-54e6-11e7-9692-95eeaf106e46.png)

![2017-06-17 16 01 16](https://user-images.githubusercontent.com/22668877/27282100-7d6c6154-54e6-11e7-86c9-43332936398b.png)

![2017-06-19 11 52 21](https://user-images.githubusercontent.com/22668877/27282095-765fd634-54e6-11e7-85af-eb8ba12f1287.png)

**Comment by amdrew** [comment]
The EDD checkout should look much nicer now (pushed some tweaks before) though the FES ones are going to be a lot harder to fix because well, tables :) However, after 1.0 I'll work on a new non-table layout for the products screen which will fix that (https://github.com/easydigitaldownloads/themedd/issues/47)

The last issue is a bit of a problem, since you can't drop the input down onto a new line. I wonder if we should tackle these FES table issues directly on the FES repo. It's probably going to look the same in any theme.

**Comment by davidsherlock** [comment]
@amdrew, I would say to close this one for the time being and when the rework happens for the FES products create a new issue.
