### ISSUE TITLE
Improved download sidebar

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#48]
One of the things Vendd theme got right was the download sidebar, if something similar (or just a straight fork of the code/widgets) could be implemented into Themedd my life would be complete! :)

It was either pre-built/set out via fallback code (download_sidebar.php), or optionally overridden using the widgets the theme included. I actually added some additional stuff to my child theme, but here is a rough idea of what it looks like at present:

![screenshot 2017-06-20 10 27 01](https://user-images.githubusercontent.com/22668877/27326393-3cc5b4b2-55a3-11e7-90e1-60748e313f43.png)

Some key points:

- Incorporating the price into the purchase button is a good idea and saves a lot of space. For variable priced (or multi-part) products, the approach in the screenshot works best. Free downloads replace the button text with just "Free Download".

- The download details widget allows space for the tags, categories, sales and software licensing information to be displayed in one neat widget. Updating this code/widget later is easy for additional extensions.

- It features a really good FES/Author social widget that shows all the social profile links, link to FES store page (clicking the avatar or store name), how long they have been an author, etc. This could again have hooks and alike to allow more info to be shown (country of vendor, total sales count, etc.).

- Other widgets like the EDD cart can be added to the side bar.

The only down side to the sidebar approach is when the user scrolls down the page (assuming it's a longer page) then the buy button isn't anywhere to be seen. This could be rectified by having something like Creative Market does (a bar that shows with the buy button when you scroll a set distance) or the way this theme does it (try scrolling with your mouse wheel): https://preview.arraythemes.com/checkout-edd/downloads/ios-crash-course/

What are your thoughts @amdrew? Would be awesome if something like this could done! :)

**Comment by davidsherlock** [comment]
As a side note, I created a feature in my theme to add product "features" (hence the track names showing here as an example) on a per product basis. This could obviously be a widget as well and I would be happy to share the code if you want to turn it into a plugin/feature within Themedd.

**Comment by amdrew** [comment]
💯 

> It was either pre-built/set out via fallback code (download_sidebar.php), or optionally overridden using the widgets the theme included.

👍 The theme should definitely show a "default" layout. The theme's user should see a nice looking/simple sidebar with no additional set up. In addition to the purchase button and price, this would show download categories and tags, and other things like "sales", current version etc like what Vendd displays.

> Incorporating the price into the purchase button is a good idea and saves a lot of space. For variable priced (or multi-part) products, the approach in the screenshot works best. Free downloads replace the button text with just "Free Download".

I'm not 100% sold on the price inside the purchase button. I believe the price should stand out to the customer and placing it inside the purchase button (which is the default EDD behaviour) can be hard to see. No matter which way it goes, either outside or inside, it's super easy to change from a child theme or custom plugin.

> The download details widget allows space for the tags, categories, sales and software licensing information to be displayed in one neat widget. Updating this code/widget later is easy for additional extensions.

👍 I'm all for the idea of being able to override the download sidebar from its default layout. I love the way Vendd does it so will definitely provide a similar approach and create 2 new widgets for Themedd. One for the download details (like Vendd) and 1 for the author details. 

> It features a really good FES/Author social widget that shows all the social profile links, link to FES store page (clicking the avatar or store name), how long they have been an author, etc. This could again have hooks and alike to allow more info to be shown (country of vendor, total sales count, etc.).

Yep, love it ❤️ 

Now's a good time to think about an official FES widget which outputs this information that all themes can use (will open an issue on that later). Once created, we can pull the duplicate code from Vendd and Themedd.

> Other widgets like the EDD cart can be added to the side bar.

Yep!

> The only down side to the sidebar approach is when the user scrolls down the page (assuming it's a longer page) then the buy button isn't anywhere to be seen. This could be rectified by having something like Creative Market does (a bar that shows with the buy button when you scroll a set distance) or the way this theme does it (try scrolling with your mouse wheel): https://preview.arraythemes.com/checkout-edd/downloads/ios-crash-course/

This kind of functionality would be best left to a child theme or custom functionality plugin.

> As a side note, I created a feature in my theme to add product "features" (hence the track names showing here as an example) on a per product basis. This could obviously be a widget as well and I would be happy to share the code if you want to turn it into a plugin/feature within Themedd.

This is also best suited as a plugin for data portability (that's why EDD Pricing Tables is a plugin). If the theme is switched, the user won't lose their pricing, or features in this case.

I built a "EDD Download Meta" plugin for the AffiliateWP and RCP sites (should probably release it at some point). It sounds like a great place to add a "features" textarea field. Like EDD Pricing Tables, you could simply put each "feature" on a new line and it will spit them out in the HTML of your choosing. Interested to hear how you created your feature functionality. Does it use repeatable fields, a textarea field, or does it use a custom taxonomy?

There's a couple of fields that are being added by the child theme. It integrates with Software licensing but will show a version field when SL is not activated.

<img width="302" alt="screenshot 2017-06-20 13 17 06" src="https://user-images.githubusercontent.com/52581/27362600-9e643622-5683-11e7-89e4-8fc160275d65.png">

<img width="392" alt="screenshot 2017-06-20 13 12 51" src="https://user-images.githubusercontent.com/52581/27362601-9e663f26-5683-11e7-942f-35142264af8f.png">

**Comment by davidsherlock** [comment]
Yeah, love the look of that sidebar on AffiliateWP! Something like that would be awesome to have.

The one I am using looks like this:

![screenshot 2017-06-21 12 40 18](https://user-images.githubusercontent.com/22668877/27382430-e337390c-567e-11e7-974a-0b901c1769a8.png)

It has fallback functions to pull data from FES repeater fields that vendors control and splits the data into separate text fields as per the screenshot.

I want to propose one more additional widget - a social sharing widget. To keep things 'light' (and bloat-free) with the theme, I propose we create a simple social sharing widget that uses no external libraries/scripts and allows sharing of products, posts, etc out of the box. This means bloat like Jetpack and other 3rd party sharing plugins isn't required.

The widget would be really simple, just the ability to select which network buttons are shown. I would only go for the popular ones - Facebook, Twitter, etc and load SVG icons to keep the page size down.

**Comment by amdrew** [comment]
So kind of like the "share this article!" at the bottom of this post but as a widget so something similar can be shown in the download sidebar or on post/pages: https://affiliatewp.com/direct-link-tracking-v1-1-released/

<img width="293" alt="screenshot 2017-06-22 15 46 17" src="https://user-images.githubusercontent.com/52581/27416504-f65696a2-5761-11e7-81ab-19cf2e5af195.png">

**Comment by davidsherlock** [comment]
Exactly that @amdrew!

**Comment by amdrew** [comment]
A bit of progress. The ultimate goal is a design that looks clean and simple out of the box. The author details and download details can be tweaked from a child theme, or with very minimal CSS.

<img width="1402" alt="screenshot 2017-06-23 15 21 12" src="https://user-images.githubusercontent.com/52581/27465459-c052ec42-5827-11e7-82ff-7305c14d81bb.png">

**Comment by davidsherlock** [comment]
Liking this a lot @amdrew, _exactly_ what I had in mind for the side bar!

**Comment by amdrew** [comment]
Made the purchase button (only on the single download page) 100% width, looks a lot better IMO.

<img width="1497" alt="screenshot 2017-06-24 10 04 23" src="https://user-images.githubusercontent.com/52581/27501934-94a2dc54-58c4-11e7-9a16-ea58306eb80b.png">

Also included a filter to have an alternate layout for the pricing (price inside button).
<img width="1492" alt="screenshot 2017-06-24 10 04 40" src="https://user-images.githubusercontent.com/52581/27501936-9bbc1028-58c4-11e7-8f21-c6a5c1328e6c.png">

Widgets are also complete!

**Comment by davidsherlock** [comment]
You are a legend @amdrew! Loving all the decisions here, and agree 100% on the full width button - looks a lot better.

One suggestion for Themedd would be that if the reviews plugin is enabled to show the "average reviews" stars on the download sidebar. This was missing from Vendd and something I felt marketplaces could benefit from.

**Comment by amdrew** [comment]
@davidsherlock Want to open a new issue for the reviews bit?

**Comment by amdrew** [comment]
Ready for testing. There's 2 new widgets like the Vendd theme to build out the download sidebar. Comes with a default layout.

**Comment by davidsherlock** [comment]
Will give this a spin today and report back any issues!

**Comment by amdrew** [comment]
Excellent!

**Comment by davidsherlock** [comment]
Because I don't have software licensing installed, I got this error:

`Fatal error: Uncaught Error: Call to undefined function edd_download_meta_has_edd_sl_enabled() in /app/public/wp-content/themes/themedd/includes/compatibility/edd/widgets.php on line 349`

<img width="724" alt="screenshot 2017-06-26 12 52 58" src="https://user-images.githubusercontent.com/22668877/27538130-81e597b8-5a6e-11e7-98ba-3eb6489db90b.png">

This only occurred when I tried to use the widgets, not with the default sidebar.

**Comment by davidsherlock** [comment]
Also @amdrew, as per the other threads if you could post the code snippets to achieve the pricing within the button, etc that would be great!

**Comment by davidsherlock** [comment]
@amdrew, i'm guessing the social media icons will come to the author widget once handled in the theme?

**Comment by amdrew** [comment]
^ Fatal error should be fixed.

> i'm guessing the social media icons will come to the author widget once handled in the theme?

Yes, social media icons will come in https://github.com/easydigitaldownloads/themedd/issues/57

**Comment by davidsherlock** [comment]
Fatal error fixed now!

**Comment by amdrew** [comment]
👍
