### ISSUE TITLE
Add EDD Cart widget to default download sidebar when widgets aren't active

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#63]
When the custom widgets aren't overriding the default download sidebar layout, I think we should also add the EDD download cart to the sidebar like Vendd does.

**Comment by amdrew** [comment]
I purposely chose not to include a cart in the sidebar in the default layout but open to any feedback on why it should be added.

I personally believe it provides an unnecessary distraction (almost a nag) to the customer, especially since there's already cart functionality in the header. It's also not something I've seen on eCommerce sites when shopping. I don't think it's a biggie since the theme's user can add it by dragging the widget to the sidebar.

The other reason is also related to it being a distraction. I think it's unfair to a point that a customer could be browsing a vendor's product, with another vendor's product already in their cart. If the customer is looking at the download sidebar they might decide to start the check out process without adding the current vendor's download to the cart (because they were reminded).
