### ISSUE TITLE
Taxonomy pages not honouring download_meta_options 

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#71]
As per the title, the category/tags taxonomy pages are not honouring the setup I have in my child theme:

```
function themedd_child_edd_download_meta_options( $options ) {

	$options['price']       = true;
	$options['price_link']  = true;
	$options['author_name'] = true;
	$options['author_link'] = true;
	$options['author_by']   = 'By';
	$options['avatar']      = true;
	$options['avatar_size'] = 32;

	return $options;

}
add_filter( 'themedd_edd_download_meta_options', 'themedd_child_edd_download_meta_options' );
```
It's currently showing like this (price displayed twice) and no purchase button:

![screenshot 2017-06-30 11 37 53](https://user-images.githubusercontent.com/22668877/27732318-9294cf26-5d88-11e7-8eb6-c3754686e82d.png)

Any ideas?

**Comment by amdrew** [comment]
That's happening because the special taxonomy pages for download categories and tags use the download grid template part: `get_template_part( 'template-parts/download-grid' )`

This template part in turn calls `edd_get_template_part( 'shortcode', 'content-price' );` which is the price you still see.

The commit above will hide the default price if the price inside the download meta is turned on.

**Comment by amdrew** [comment]
Hmm looking into why the purchase button isn't showing, it should match the output of the `/downloads` custom post type archive

**Comment by amdrew** [comment]
@davidsherlock That should do it
