### ISSUE TITLE
Center blog post title/subtitle

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#81]
Since the pages have the title centered, I feel it makes sense to also center the blog post title/subtitle the same.

**Comment by amdrew** [comment]
The headings on pages are only centered when there's no sidebar (no widgets being used). On a default page with sidebar, the heading is left aligned. Posts are also left aligned when there is a sidebar, and centered when there isn't a sidebar.

**Comment by SDavisMedia** [comment]
Just to randomly chime in here with a general opinion that doesn't really apply to Themedd specifically, I don't think it's a good move to always do something on a post just because it's done on a page, and vice versa.

99% of the time, theme developers make both of them look exactly alike (besides a bit of post meta display). That's completely unnecessary and honestly stems from a lack of thought and creativity, in my opinion. I'm toootally guilty of it, like most theme devs are. But the idea that they need to have the same structure is based on nothing and shouldn't be viewed as an inconsistency if you ask me.

**Comment by davidsherlock** [comment]
@amdrew, close this one off - taking care of it via my version of the theme.

**Comment by amdrew** [comment]
👍

**Comment by amdrew** [comment]
Re-opening. I might center page and post headings regardless. A few reasons:

1. Having the headings left aligned when there is no sidebar might cause some confusion.
2. Themedd is designed to be a "starting point". This is probably a design decision best left for the child theme.
3. Consistency.

I can always provide a code snippet to show someone how to left align headings when there is no sidebar.
