### ISSUE TITLE
themedd_is_edd_commissions_active() function required

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#85]
Can this function be added to the functions.php file please?

```
/**
 * Is EDD Commissions active?
 *
 * @since 1.0.0
 * @return bool
 */
function themedd_is_edd_commissions_active() {
	return class_exists( 'EDD_Commission' );
}
```

**Comment by amdrew** [comment]
@davidsherlock Can you elaborate a bit more on why you think it is required? I'm hesitant to add that since themedd does not alter any code from the Commissions extension (only styling changes). All other functions that check for extensions are there because there's code related to those extensions. 

At this point, it would be better to include the function in a child theme if the child theme is modifying any functionality within commissions.

**Comment by davidsherlock** [comment]
@amdrew, I was actually building an account page template that used tabs (similar to what you have with AffiliateWP) and wanted to include a commissions tab hence this request.

I'm fine including it in my child theme, just felt it would be useful to be able to check all EDD extensions from within the parent theme for convenience purposes.

**Comment by amdrew** [comment]
@davidsherlock 👍 I'll add it once it's needed by the parent theme.
