### ISSUE TITLE
function themedd_edd_downloads_shortcode issue

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/themedd#90]
@amdrew, after much searching I discovered the reason for the Javascript issue I was facing. Because this function (themedd_edd_downloads_shortcode issue) checks the EDD version number and skips it for version 2.8, it breaks the layout for my theme. Obviously including this function in my theme fixes the issue. I was wondering the reason for this?

I'm aware 2.8 introduces a new template file, but the actual output of EDD is messy (with clears, etc) and your method is better. Just curious to know the reason for not using your method when it's cleaner and better than core EDD.

**Comment by amdrew** [comment]
@davidsherlock What was the exact cause of your issue? Just not seeing how the `themedd_edd_downloads_shortcode` function vs the `shortcode-download.php` template file could affect JS and break a layout. Let me know and I'll see if there's anything we can do to improve that.

> I'm aware 2.8 introduces a new template file, but the actual output of EDD is messy (with clears, etc) and your method is better. Just curious to know the reason for not using your method when it's cleaner and better than core EDD.

Good question. I'm using the new `shortcode-download.php` template file (and thus the reason for the conditional check in the `themedd_edd_downloads_shortcode()` function) for a few reasons:

1. So a child theme can more easily override the template file. Rather than the child theme having to first remove the filter Themedd includes, add it back with all the modifications etc. It's just simpler for someone to understand a template file vs a filter. It will also save a few support tickets in the future when the template file is more commonly used, since if someone used the new template file, the filter would still be overriding it, which will lead to confusion.
2. Although there's nothing wrong with the filter (I like the cleaner markup) it includes some code that doesn't need to be repeated such as the pagination code. EDD should handle this, and maintenance will be slightly harder in the future if something changes in EDD core surrounding the download grid.
3. Because the clearing divs will be eventually removed in the future. I'm championing this over at:  https://github.com/easydigitaldownloads/easy-digital-downloads/issues/5847

**Comment by davidsherlock** [comment]
Thanks for your feedback Andrew! 

I have two potential theories:

1. My first theory is the "clears" are being counted as elements by slick.js and breaking the layout.

2. Potentially the priority of your function might be causing a race condition with the slick.js when not used. This is less likely but I can't figure out any other potential reason because your markup is identical to EDD, minus clears.

Any ideas yourself? At the minute if I don't use your function I walk into problems with slick.js.

**Comment by amdrew** [comment]
@davidsherlock I can't say for sure since I haven't implemented slick.js but I'd say it's likely 1. 

Do this: 

1. Make sure you're using the new template file.
2. Remove the clearing divs from EDD core on your local machine
3. See if everything works as expected.

**Comment by davidsherlock** [comment]
You can close this one @amdrew, it's related to the clears.

**Comment by amdrew** [comment]
👍
